# Use an official Node.js runtime as a parent image
FROM node:19-alpine

# Set the working directory to /app
WORKDIR /home/app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install


# Copy the rest of the application code to the container
COPY . .

# Build the React app for production
RUN npm run build

# Expose the port on which the app will be running
EXPOSE 3000

#RUN npm uninstall -g serve
RUN npm install -g serve

# Start the app
CMD ["serve", "-s","build"]
#CMD ["npm", "start"]